# Generated by Django 4.0.2 on 2022-02-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('API_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.TextField()),
                ('ingredients', models.JSONField()),
                ('Instructions', models.JSONField()),
            ],
        ),
    ]
