# Generated by Django 4.0.2 on 2022-02-05 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_instructions_recipe_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentRecipe',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 primary_key=True, serialize=False, to='recipe.recipe')),
            ],
        ),
    ]
