# Generated by Django 4.0.2 on 2022-02-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_currentrecipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentrecipe',
            old_name='id',
            new_name='recipe',
        ),
    ]
