# Generated by Django 4.0.2 on 2022-02-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_rename_id_currentrecipe_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentrecipe',
            name='recipe',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
